# Generated by Django 5.1.5 on 2025-02-04 13:51

import django.contrib.gis.db.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_event_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.RemoveField(
            model_name="event",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="event",
            name="longitude",
        ),
        migrations.AddField(
            model_name="event",
            name="coordinates",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["coordinates"], name="events_even_coordin_41730c_idx"
            ),
        ),
    ]
