# Generated by Django 5.1.5 on 2025-02-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_alter_category_options_remove_event_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="price",
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
