# Generated by Django 5.1.5 on 2025-02-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_event_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="website",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
