# Generated by Django 5.1.5 on 2025-02-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_event_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("approved", "approved"),
                    ("rejected", "rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="price",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
