# Generated by Django 5.1.5 on 2025-02-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_event_status_alter_event_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
