# Generated by Django 5.1.5 on 2025-02-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_alter_event_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
